#!/usr/bin/env bash
# Federation One-Click Setup
# Automates the entire workshop tutorial in one script.
#
# Usage:
#   ./federation-setup.sh                # Interactive setup
#   ./federation-setup.sh --check        # Check if already set up
#   ./federation-setup.sh --uninstall    # Remove federation config
#
# 🤖 Generated by Federation Oracle 🗺️

set -euo pipefail

# Colors
if [[ -t 1 ]]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
  BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'
else
  RED='' GREEN='' YELLOW='' BLUE='' CYAN='' NC=''
fi

CONFIG_DIR="$HOME/.config/maw"
CONFIG_FILE="$CONFIG_DIR/maw.config.json"

banner() {
  echo ""
  echo -e "${CYAN}🗺️  Federation Setup${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
}

check_mode() {
  banner
  echo "Checking federation setup..."
  echo ""

  # Bun
  if command -v bun &>/dev/null; then
    echo -e "  ${GREEN}✅${NC} Bun: $(bun --version)"
  else
    echo -e "  ${RED}❌${NC} Bun: not installed"
  fi

  # maw
  if command -v maw &>/dev/null; then
    echo -e "  ${GREEN}✅${NC} maw: $(maw --version 2>/dev/null || echo 'installed but version unknown')"
  else
    echo -e "  ${RED}❌${NC} maw: not installed"
  fi

  # Config
  if [[ -f "$CONFIG_FILE" ]]; then
    NODE=$(jq -r '.node // "?"' "$CONFIG_FILE")
    PORT=$(jq -r '.port // "?"' "$CONFIG_FILE")
    HOST=$(jq -r '.host // "?"' "$CONFIG_FILE")
    TOKEN_LEN=$(jq -r '.federationToken | length' "$CONFIG_FILE")
    PEERS=$(jq -r '.namedPeers | length' "$CONFIG_FILE")
    echo -e "  ${GREEN}✅${NC} Config: $CONFIG_FILE"
    echo -e "       node=$NODE, port=$PORT, host=$HOST"
    echo -e "       token=${TOKEN_LEN} chars, peers=$PEERS"

    if [[ "$HOST" != "0.0.0.0" ]]; then
      echo -e "  ${YELLOW}⚠️${NC}  host should be 0.0.0.0 for federation"
    fi
    if [[ "$TOKEN_LEN" -lt 16 ]]; then
      echo -e "  ${YELLOW}⚠️${NC}  token should be ≥16 chars"
    fi
  else
    echo -e "  ${RED}❌${NC} Config: not found"
  fi

  # Serving
  PORT_NUM=$(jq -r '.port // 3456' "$CONFIG_FILE" 2>/dev/null || echo 3456)
  if curl -sf --max-time 2 "http://localhost:$PORT_NUM/api/identity" > /dev/null 2>&1; then
    echo -e "  ${GREEN}✅${NC} maw serve: running on port $PORT_NUM"
  else
    echo -e "  ${RED}❌${NC} maw serve: not running"
  fi

  echo ""
}

uninstall_mode() {
  banner
  echo -e "${YELLOW}This will remove your federation config.${NC}"
  echo "File: $CONFIG_FILE"
  echo ""

  if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "No config found. Nothing to remove."
    exit 0
  fi

  echo -n "Create backup first? [Y/n]: "
  read -r backup
  if [[ "${backup:-Y}" != "n" ]]; then
    BACKUP="$CONFIG_FILE.bak.$(date +%s)"
    cp "$CONFIG_FILE" "$BACKUP"
    echo -e "${GREEN}Backed up to:${NC} $BACKUP"
  fi

  echo -n "Remove $CONFIG_FILE? [y/N]: "
  read -r confirm
  if [[ "$confirm" == "y" ]]; then
    rm "$CONFIG_FILE"
    echo -e "${GREEN}Config removed.${NC}"

    if command -v pm2 &>/dev/null && pm2 list 2>/dev/null | grep -q maw; then
      echo -n "Stop pm2 maw process? [y/N]: "
      read -r stop_pm2
      if [[ "$stop_pm2" == "y" ]]; then
        pm2 delete maw 2>/dev/null || true
        pm2 save 2>/dev/null || true
        echo "pm2 maw stopped."
      fi
    fi
  else
    echo "Cancelled."
  fi
}

setup_mode() {
  banner
  echo "This script will set up federation on this machine."
  echo "It takes about 2 minutes."
  echo ""

  # Step 1: Check Bun
  echo -e "${CYAN}Step 1: Checking Bun${NC}"
  if command -v bun &>/dev/null; then
    echo -e "  ${GREEN}✅${NC} Bun $(bun --version) found"
  else
    echo -e "  ${RED}❌${NC} Bun not found"
    echo ""
    echo "Install Bun first:"
    echo "  curl -fsSL https://bun.sh/install | bash"
    echo ""
    echo "Then re-run this script."
    exit 1
  fi

  # Step 2: Check/Install maw
  echo -e "${CYAN}Step 2: Checking maw${NC}"
  if command -v maw &>/dev/null; then
    echo -e "  ${GREEN}✅${NC} maw $(maw --version 2>/dev/null || echo 'found')"
  else
    echo -e "  ${YELLOW}⚠️${NC}  maw not found — installing..."
    echo ""
    echo -n "Install maw from source? [Y/n]: "
    read -r install_maw
    if [[ "${install_maw:-Y}" != "n" ]]; then
      INSTALL_DIR="${MAW_INSTALL_DIR:-$HOME/maw-js}"
      if [[ -d "$INSTALL_DIR" ]]; then
        echo "  Using existing: $INSTALL_DIR"
      else
        echo "  Cloning to: $INSTALL_DIR"
        git clone https://github.com/Soul-Brews-Studio/maw-js "$INSTALL_DIR"
      fi
      cd "$INSTALL_DIR"
      bun install
      bun link
      cd - > /dev/null

      if command -v maw &>/dev/null; then
        echo -e "  ${GREEN}✅${NC} maw installed"
      else
        ln -sf "$INSTALL_DIR/src/cli.ts" "$HOME/.bun/bin/maw"
        echo -e "  ${GREEN}✅${NC} maw linked to ~/.bun/bin/maw"
      fi
    else
      echo "  Skipping maw install. You'll need it later."
    fi
  fi

  # Step 3: Node name
  echo ""
  echo -e "${CYAN}Step 3: Configure this machine${NC}"
  HOSTNAME=$(hostname -s 2>/dev/null | tr '[:upper:]' '[:lower:]' || echo "my-machine")
  echo -n "  Node name [$HOSTNAME]: "
  read -r NODE_NAME
  NODE_NAME="${NODE_NAME:-$HOSTNAME}"

  # Step 4: Port
  echo -n "  Port [3456]: "
  read -r PORT
  PORT="${PORT:-3456}"

  # Step 5: Token
  echo ""
  echo -e "${CYAN}Step 4: Federation token${NC}"
  echo "  The token is a shared secret. All machines in your"
  echo "  federation need the exact same token."
  echo ""
  echo -n "  Enter existing token (or press Enter to generate new): "
  read -r TOKEN
  if [[ -z "$TOKEN" ]]; then
    TOKEN=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))" 2>/dev/null || echo "please-change-this-token-$(date +%s)")
    echo -e "  ${GREEN}Generated:${NC} $TOKEN"
    echo ""
    echo -e "  ${YELLOW}Save this token!${NC} Your other machines need it."
  fi

  # Step 6: Peers
  echo ""
  echo -e "${CYAN}Step 5: Add peers${NC}"
  echo "  Enter peer machines. Leave blank when done."
  echo ""

  PEERS_JSON="[]"
  PEER_NUM=1
  while true; do
    echo -n "  Peer $PEER_NUM name (blank to finish): "
    read -r PEER_NAME
    [[ -z "$PEER_NAME" ]] && break

    echo -n "  Peer $PEER_NUM IP: "
    read -r PEER_IP
    [[ -z "$PEER_IP" ]] && break

    echo -n "  Peer $PEER_NUM port [$PORT]: "
    read -r PEER_PORT
    PEER_PORT="${PEER_PORT:-$PORT}"

    PEERS_JSON=$(echo "$PEERS_JSON" | jq ". + [{\"name\": \"$PEER_NAME\", \"url\": \"http://$PEER_IP:$PEER_PORT\"}]")
    echo -e "  ${GREEN}✅${NC} Added: $PEER_NAME → http://$PEER_IP:$PEER_PORT"
    echo ""
    PEER_NUM=$((PEER_NUM + 1))
  done

  # Step 7: Write config
  echo ""
  echo -e "${CYAN}Step 6: Writing config${NC}"
  mkdir -p "$CONFIG_DIR"

  if [[ -f "$CONFIG_FILE" ]]; then
    BACKUP="$CONFIG_FILE.bak.$(date +%s)"
    cp "$CONFIG_FILE" "$BACKUP"
    echo -e "  ${YELLOW}Backed up existing:${NC} $BACKUP"
  fi

  cat > "$CONFIG_FILE" << ENDCONFIG
{
  "node": "$NODE_NAME",
  "port": $PORT,
  "host": "0.0.0.0",
  "federationToken": "$TOKEN",
  "namedPeers": $(echo "$PEERS_JSON" | jq .),
  "agents": {}
}
ENDCONFIG

  chmod 600 "$CONFIG_FILE"
  echo -e "  ${GREEN}✅${NC} Written: $CONFIG_FILE"
  echo -e "  ${GREEN}✅${NC} Permissions: 600 (owner-only)"

  # Step 8: Start serving
  echo ""
  echo -e "${CYAN}Step 7: Start maw serve${NC}"

  if curl -sf --max-time 2 "http://localhost:$PORT/api/identity" > /dev/null 2>&1; then
    echo -e "  ${YELLOW}⚠️${NC}  maw already serving on port $PORT"
    echo -n "  Restart? [y/N]: "
    read -r restart
    if [[ "$restart" == "y" ]] && command -v pm2 &>/dev/null; then
      pm2 restart maw 2>/dev/null || true
    fi
  else
    echo -n "  Start maw serve now? [Y/n]: "
    read -r start_maw
    if [[ "${start_maw:-Y}" != "n" ]]; then
      if command -v pm2 &>/dev/null; then
        pm2 start maw --interpreter bun -- serve 2>/dev/null || maw serve &
        pm2 save 2>/dev/null || true
        echo -e "  ${GREEN}✅${NC} Started with pm2"
      else
        maw serve &
        echo -e "  ${GREEN}✅${NC} Started (background process)"
        echo -e "  ${YELLOW}Tip:${NC} Install pm2 for persistence: bun add -g pm2"
      fi
      sleep 2
    fi
  fi

  # Step 9: Verify
  echo ""
  echo -e "${CYAN}Step 8: Verify${NC}"
  if curl -sf --max-time 3 "http://localhost:$PORT/api/identity" > /dev/null 2>&1; then
    echo -e "  ${GREEN}✅${NC} maw serve is running"
    IDENTITY=$(curl -sf "http://localhost:$PORT/api/identity" | jq -r '.node')
    echo -e "  ${GREEN}✅${NC} Node identity: $IDENTITY"
  else
    echo -e "  ${YELLOW}⚠️${NC}  maw serve not responding (may still be starting)"
  fi

  PEER_COUNT=$(echo "$PEERS_JSON" | jq length)
  if [[ "$PEER_COUNT" -gt 0 ]]; then
    echo ""
    echo "  Checking peers..."
    maw federation status 2>/dev/null || echo "  (run 'maw federation status' once peers are online)"
  fi

  # Done
  echo ""
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${GREEN}Setup complete!${NC}"
  echo ""
  echo "Your node: $NODE_NAME on port $PORT"
  echo "Token: $TOKEN"
  echo "Peers: $PEER_COUNT configured"
  echo ""
  echo "Next steps:"
  echo "  1. Run this script on your other machine(s)"
  echo "  2. Use the SAME token: $TOKEN"
  echo "  3. Check: maw federation status"
  echo "  4. Send: maw hey PEER:SESSION \"hello!\""
  echo ""
  echo -e "🗺️  ${CYAN}Welcome to the federation!${NC}"
}

# Main
case "${1:-}" in
  --check)    check_mode ;;
  --uninstall) uninstall_mode ;;
  --help|-h)
    echo "Usage: $0 [--check|--uninstall|--help]"
    echo "  (no args)    Interactive setup"
    echo "  --check      Check current setup"
    echo "  --uninstall  Remove federation config"
    ;;
  *)          setup_mode ;;
esac
