#!/usr/bin/env bash
# Federation Message Sender
# Send authenticated messages to federation peers without maw CLI.
# Useful for scripting, cron jobs, and non-maw environments.
#
# Usage:
#   ./federation-send.sh <peer_url> <target> <message>
#   ./federation-send.sh http://192.168.1.101:3456 my-oracle "Hello!"
#
# Environment:
#   MAW_TOKEN    Override federation token (default: read from config)
#   MAW_CONFIG   Override config path (default: ~/.config/maw/maw.config.json)
#
# 🤖 Generated by Federation Oracle 🗺️

set -euo pipefail

# Parse args
if [[ $# -lt 3 ]]; then
  echo "Usage: $0 <peer_url> <target> <message>"
  echo ""
  echo "Examples:"
  echo "  $0 http://192.168.1.101:3456 my-oracle 'Hello!'"
  echo "  $0 http://desktop:3456 code-review 'Please review PR #42'"
  echo ""
  echo "Environment variables:"
  echo "  MAW_TOKEN   Federation token (overrides config)"
  echo "  MAW_CONFIG  Config file path (default: ~/.config/maw/maw.config.json)"
  exit 1
fi

PEER_URL="$1"
TARGET="$2"
MESSAGE="$3"
CONFIG="${MAW_CONFIG:-$HOME/.config/maw/maw.config.json}"

# Get token
if [[ -n "${MAW_TOKEN:-}" ]]; then
  TOKEN="$MAW_TOKEN"
elif [[ -f "$CONFIG" ]]; then
  TOKEN=$(jq -r '.federationToken // empty' "$CONFIG")
  if [[ -z "$TOKEN" ]]; then
    echo "Error: No federationToken in $CONFIG" >&2
    echo "Set MAW_TOKEN or add federationToken to config" >&2
    exit 2
  fi
else
  echo "Error: No config at $CONFIG and MAW_TOKEN not set" >&2
  exit 2
fi

# Compute HMAC signature
TIMESTAMP=$(date +%s)
PATH_STR="/api/send"
SIGN_STRING="POST:${PATH_STR}:${TIMESTAMP}"

# Try openssl first, fall back to python
if command -v openssl &>/dev/null; then
  SIGNATURE=$(echo -n "$SIGN_STRING" | openssl dgst -sha256 -hmac "$TOKEN" -hex 2>/dev/null | awk '{print $NF}')
elif command -v python3 &>/dev/null; then
  SIGNATURE=$(python3 -c "
import hmac, hashlib
sig = hmac.new('$TOKEN'.encode(), '$SIGN_STRING'.encode(), hashlib.sha256).hexdigest()
print(sig)
")
else
  echo "Error: Need openssl or python3 for HMAC computation" >&2
  exit 3
fi

# Send the request
RESPONSE=$(curl -sf -X POST "${PEER_URL}${PATH_STR}" \
  -H "Content-Type: application/json" \
  -H "X-Maw-Signature: ${SIGNATURE}" \
  -H "X-Maw-Timestamp: ${TIMESTAMP}" \
  -d "{\"target\": \"${TARGET}\", \"message\": \"${MESSAGE}\"}" \
  2>&1) || {
    EXIT_CODE=$?
    if [[ $EXIT_CODE -eq 22 ]]; then
      echo "Error: HTTP error (likely 403 — check token)" >&2
    elif [[ $EXIT_CODE -eq 7 ]]; then
      echo "Error: Connection refused — is maw serve running at ${PEER_URL}?" >&2
    elif [[ $EXIT_CODE -eq 28 ]]; then
      echo "Error: Timeout — check network connectivity" >&2
    else
      echo "Error: curl failed with exit code $EXIT_CODE" >&2
    fi
    exit 4
  }

# Parse response
STATUS=$(echo "$RESPONSE" | jq -r '.status // "unknown"' 2>/dev/null || echo "unknown")

if [[ "$STATUS" == "delivered" ]]; then
  echo "✅ delivered → ${TARGET} on $(echo "$PEER_URL" | sed 's|http://||')"
elif [[ "$STATUS" == "error" ]]; then
  ERROR=$(echo "$RESPONSE" | jq -r '.error // "unknown error"' 2>/dev/null)
  echo "❌ $ERROR" >&2
  exit 5
else
  echo "Response: $RESPONSE"
fi
