#!/usr/bin/env bash
# Federation Config Validator
# Validates maw.config.json for common issues before you start serving.
#
# Usage:
#   ./federation-validate.sh                     # Validate local config
#   ./federation-validate.sh /path/to/config.json  # Validate specific file
#   ./federation-validate.sh --fix               # Fix common issues interactively
#
# 🤖 Generated by Federation Oracle 🗺️

set -euo pipefail

# Colors
if [[ -t 1 ]]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
  CYAN='\033[0;36m'; NC='\033[0m'
else
  RED='' GREEN='' YELLOW='' CYAN='' NC=''
fi

CONFIG="${1:-$HOME/.config/maw/maw.config.json}"
FIX_MODE=false

if [[ "${1:-}" == "--fix" ]]; then
  FIX_MODE=true
  CONFIG="$HOME/.config/maw/maw.config.json"
fi

ERRORS=0
WARNINGS=0

pass() { echo -e "  ${GREEN}✅${NC} $1"; }
warn() { echo -e "  ${YELLOW}⚠️${NC}  $1"; WARNINGS=$((WARNINGS + 1)); }
fail() { echo -e "  ${RED}❌${NC} $1"; ERRORS=$((ERRORS + 1)); }

echo ""
echo -e "${CYAN}🗺️  Federation Config Validator${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Config: $CONFIG"
echo ""

# Check file exists
if [[ ! -f "$CONFIG" ]]; then
  fail "Config file not found: $CONFIG"
  echo ""
  echo "Create one with:"
  echo '  mkdir -p ~/.config/maw'
  echo '  Run: scripts/federation-config-gen.sh'
  exit 1
fi

# Check valid JSON
if ! jq . "$CONFIG" > /dev/null 2>&1; then
  fail "Invalid JSON in config file"
  echo ""
  echo "Fix: Check for trailing commas, missing quotes, or syntax errors"
  exit 1
fi
pass "Valid JSON"

# Check required fields
echo ""
echo "Required Fields:"

# node
NODE=$(jq -r '.node // empty' "$CONFIG")
if [[ -z "$NODE" ]]; then
  fail "Missing 'node' field (your machine's unique name)"
else
  pass "node: \"$NODE\""
fi

# port
PORT=$(jq -r '.port // empty' "$CONFIG")
if [[ -z "$PORT" ]]; then
  fail "Missing 'port' field"
elif ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
  fail "port must be a number, got: \"$PORT\""
elif [[ "$PORT" -lt 1024 ]] || [[ "$PORT" -gt 65535 ]]; then
  warn "port $PORT is unusual (typical: 3456-3460)"
else
  pass "port: $PORT"
fi

# host
HOST=$(jq -r '.host // empty' "$CONFIG")
if [[ -z "$HOST" ]]; then
  fail "Missing 'host' field — add '\"host\": \"0.0.0.0\"' for federation"
elif [[ "$HOST" == "local" ]] || [[ "$HOST" == "localhost" ]] || [[ "$HOST" == "127.0.0.1" ]]; then
  fail "host is \"$HOST\" — remote peers CAN'T reach you! Change to \"0.0.0.0\""
  if $FIX_MODE; then
    echo -n "    Fix to 0.0.0.0? [y/N]: "
    read -r yn
    if [[ "$yn" == "y" ]]; then
      jq '.host = "0.0.0.0"' "$CONFIG" > /tmp/maw-fix.json && mv /tmp/maw-fix.json "$CONFIG"
      echo -e "    ${GREEN}Fixed!${NC}"
      ERRORS=$((ERRORS - 1))
    fi
  fi
elif [[ "$HOST" == "0.0.0.0" ]]; then
  pass "host: \"0.0.0.0\" (accepts remote connections)"
else
  warn "host: \"$HOST\" — only accepts connections on this interface"
fi

# federationToken
TOKEN=$(jq -r '.federationToken // empty' "$CONFIG")
TOKEN_LEN=${#TOKEN}
if [[ -z "$TOKEN" ]]; then
  fail "Missing or empty 'federationToken' — federation is UNAUTHENTICATED"
  if $FIX_MODE; then
    echo -n "    Generate a random token? [y/N]: "
    read -r yn
    if [[ "$yn" == "y" ]]; then
      NEW_TOKEN=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))")
      jq ".federationToken = \"$NEW_TOKEN\"" "$CONFIG" > /tmp/maw-fix.json && mv /tmp/maw-fix.json "$CONFIG"
      echo -e "    ${GREEN}Token set: $NEW_TOKEN${NC}"
      echo -e "    ${YELLOW}Copy this token to ALL other nodes!${NC}"
      ERRORS=$((ERRORS - 1))
    fi
  fi
elif [[ "$TOKEN_LEN" -lt 16 ]]; then
  fail "federationToken is only $TOKEN_LEN chars (minimum: 16)"
elif [[ "$TOKEN_LEN" -lt 32 ]]; then
  warn "federationToken is $TOKEN_LEN chars (recommended: ≥32 for production)"
else
  pass "federationToken: $TOKEN_LEN chars"
fi

# namedPeers
echo ""
echo "Peers:"
PEER_COUNT=$(jq '.namedPeers | length' "$CONFIG")
if [[ "$PEER_COUNT" -eq 0 ]]; then
  warn "No namedPeers configured — federation is solo (no one to talk to)"
else
  pass "$PEER_COUNT peer(s) configured"

  # Validate each peer
  for i in $(seq 0 $((PEER_COUNT - 1))); do
    PEER_NAME=$(jq -r ".namedPeers[$i].name" "$CONFIG")
    PEER_URL=$(jq -r ".namedPeers[$i].url" "$CONFIG")

    # Check URL format
    if [[ ! "$PEER_URL" =~ ^https?:// ]]; then
      fail "Peer \"$PEER_NAME\": URL missing http:// prefix: $PEER_URL"
    elif [[ "$PEER_URL" =~ /$ ]]; then
      warn "Peer \"$PEER_NAME\": URL has trailing slash: $PEER_URL"
    else
      # Try to reach peer
      if curl -sf --max-time 3 "$PEER_URL/api/identity" > /dev/null 2>&1; then
        PEER_NODE=$(curl -sf --max-time 3 "$PEER_URL/api/identity" | jq -r '.node // "?"')
        if [[ "$PEER_NODE" != "$PEER_NAME" ]]; then
          warn "Peer \"$PEER_NAME\" responds as \"$PEER_NODE\" (name mismatch)"
        else
          pass "Peer \"$PEER_NAME\" ($PEER_URL) — reachable ✅"
        fi
      else
        warn "Peer \"$PEER_NAME\" ($PEER_URL) — unreachable (may be offline)"
      fi
    fi

    # Check for duplicate names
    DUP_COUNT=$(jq "[.namedPeers[] | select(.name == \"$PEER_NAME\")] | length" "$CONFIG")
    if [[ "$DUP_COUNT" -gt 1 ]]; then
      fail "Duplicate peer name: \"$PEER_NAME\" appears $DUP_COUNT times"
    fi

    # Self-reference check
    if [[ "$PEER_NAME" == "$NODE" ]]; then
      warn "Peer \"$PEER_NAME\" has same name as this node — self-reference?"
    fi
  done
fi

# Config permissions
echo ""
echo "Security:"
PERMS=$(stat -f "%Lp" "$CONFIG" 2>/dev/null || stat -c "%a" "$CONFIG" 2>/dev/null || echo "unknown")
if [[ "$PERMS" == "600" ]]; then
  pass "File permissions: $PERMS (owner-only)"
elif [[ "$PERMS" == "644" ]] || [[ "$PERMS" == "664" ]]; then
  warn "File permissions: $PERMS — consider 'chmod 600 $CONFIG' (token is readable by group/others)"
  if $FIX_MODE; then
    echo -n "    Fix permissions to 600? [y/N]: "
    read -r yn
    if [[ "$yn" == "y" ]]; then
      chmod 600 "$CONFIG"
      echo -e "    ${GREEN}Fixed!${NC}"
      WARNINGS=$((WARNINGS - 1))
    fi
  fi
elif [[ "$PERMS" != "unknown" ]]; then
  pass "File permissions: $PERMS"
fi

# Check if maw serve is running
echo ""
echo "Runtime:"
if curl -sf --max-time 2 "http://localhost:${PORT:-3456}/api/identity" > /dev/null 2>&1; then
  SERVING_NODE=$(curl -sf --max-time 2 "http://localhost:${PORT:-3456}/api/identity" | jq -r '.node // "?"')
  if [[ "$SERVING_NODE" == "$NODE" ]]; then
    pass "maw serve is running (node: $SERVING_NODE)"
  else
    fail "maw serve is running but as \"$SERVING_NODE\", not \"$NODE\" (zombie process?)"
  fi
else
  warn "maw serve is NOT running on port ${PORT:-3456}"
fi

# Summary
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
if [[ $ERRORS -eq 0 ]] && [[ $WARNINGS -eq 0 ]]; then
  echo -e "${GREEN}All checks passed!${NC} Your federation config is ready."
elif [[ $ERRORS -eq 0 ]]; then
  echo -e "${YELLOW}$WARNINGS warning(s)${NC}, no errors. Config is usable but could be improved."
else
  echo -e "${RED}$ERRORS error(s)${NC}, $WARNINGS warning(s). Fix errors before starting federation."
fi
echo ""
