#!/usr/bin/env bash
# Federation Health Check Script
# Run manually or via cron to monitor federation status
#
# Usage:
#   ./federation-health.sh                    # Check all peers
#   ./federation-health.sh --json             # JSON output
#   ./federation-health.sh --quiet            # Exit code only (0=healthy, 1=degraded)
#   ./federation-health.sh --alert            # Alert if any peer is down
#   ./federation-health.sh --watch            # Continuous monitoring (every 30s)
#
# Crontab example (check every 5 min):
#   */5 * * * * /path/to/federation-health.sh --quiet || echo "Federation degraded" | mail -s "Alert" you@email.com
#
# 🤖 Generated by Federation Oracle 🗺️

set -euo pipefail

# Colors (disabled if not tty)
if [[ -t 1 ]]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  CYAN='\033[0;36m'
  NC='\033[0m'
else
  RED='' GREEN='' YELLOW='' CYAN='' NC=''
fi

CONFIG="${MAW_CONFIG:-$HOME/.config/maw/maw.config.json}"
TIMEOUT=5

# Parse args
MODE="default"
for arg in "$@"; do
  case "$arg" in
    --json)   MODE="json" ;;
    --quiet)  MODE="quiet" ;;
    --alert)  MODE="alert" ;;
    --watch)  MODE="watch" ;;
    --help|-h)
      echo "Usage: $0 [--json|--quiet|--alert|--watch]"
      echo ""
      echo "  --json    Output as JSON"
      echo "  --quiet   Exit code only (0=healthy, 1=degraded)"
      echo "  --alert   Send alert via maw if any peer is down"
      echo "  --watch   Continuous monitoring (every 30s)"
      echo ""
      exit 0
      ;;
  esac
done

# Read config
if [[ ! -f "$CONFIG" ]]; then
  echo "Config not found: $CONFIG" >&2
  exit 2
fi

NODE=$(jq -r '.node // "unknown"' "$CONFIG")
PORT=$(jq -r '.port // 3456' "$CONFIG")
PEERS=$(jq -r '.namedPeers // [] | .[] | "\(.name)|\(.url)"' "$CONFIG")

check_peers() {
  local healthy=0
  local total=0
  local unhealthy_list=""
  local results=""

  # Check local
  local_status="unknown"
  local_identity=$(curl -sf --max-time "$TIMEOUT" "http://localhost:$PORT/api/identity" 2>/dev/null) || true
  if [[ -n "$local_identity" ]]; then
    local_node=$(echo "$local_identity" | jq -r '.node // "?"')
    local_status="up"
  else
    local_status="down"
    local_node="$NODE"
  fi

  # Check peers
  while IFS='|' read -r peer_name peer_url; do
    [[ -z "$peer_name" ]] && continue
    total=$((total + 1))

    peer_identity=$(curl -sf --max-time "$TIMEOUT" "$peer_url/api/identity" 2>/dev/null) || true

    if [[ -n "$peer_identity" ]]; then
      peer_node=$(echo "$peer_identity" | jq -r '.node // "?"')
      peer_status="up"
      healthy=$((healthy + 1))
    else
      peer_node="?"
      peer_status="down"
      unhealthy_list="$unhealthy_list $peer_name"
    fi

    results="$results|$peer_name|$peer_url|$peer_status|$peer_node"
  done <<< "$PEERS"

  # Output based on mode
  case "$MODE" in
    json)
      echo "{"
      echo "  \"node\": \"$NODE\","
      echo "  \"local\": \"$local_status\","
      echo "  \"healthy\": $healthy,"
      echo "  \"total\": $total,"
      echo "  \"timestamp\": $(date +%s),"
      echo "  \"peers\": ["
      local first=true
      while IFS='|' read -r _ name url status identity; do
        [[ -z "$name" ]] && continue
        if [[ "$first" == "true" ]]; then
          first=false
        else
          echo ","
        fi
        printf '    {"name": "%s", "url": "%s", "status": "%s", "identity": "%s"}' "$name" "$url" "$status" "$identity"
      done <<< "$results"
      echo ""
      echo "  ]"
      echo "}"
      ;;

    quiet)
      if [[ $healthy -eq $total ]] && [[ "$local_status" == "up" ]]; then
        exit 0
      else
        exit 1
      fi
      ;;

    alert)
      if [[ -n "$unhealthy_list" ]]; then
        echo -e "${RED}ALERT:${NC} Unhealthy peers:$unhealthy_list"
        # Try to alert via maw
        if command -v maw &>/dev/null; then
          maw hey "$NODE:federation" "HEALTH ALERT: Peers down:$unhealthy_list at $(date)" 2>/dev/null || true
        fi
      else
        echo -e "${GREEN}All peers healthy${NC}"
      fi
      ;;

    watch)
      while true; do
        clear
        echo -e "${CYAN}🗺️  Federation Health — $(date)${NC}"
        echo ""
        MODE="default" check_peers_display "$local_status" "$local_node" "$healthy" "$total" "$results"
        echo ""
        echo -e "${YELLOW}Refreshing in 30s... (Ctrl+C to stop)${NC}"
        sleep 30
      done
      ;;

    *)
      check_peers_display "$local_status" "$local_node" "$healthy" "$total" "$results"
      ;;
  esac

  if [[ $healthy -lt $total ]] || [[ "$local_status" != "up" ]]; then
    return 1
  fi
  return 0
}

check_peers_display() {
  local local_status="$1"
  local local_node="$2"
  local healthy="$3"
  local total="$4"
  local results="$5"

  echo -e "${CYAN}🗺️  Federation Health Check${NC}"
  echo ""

  # Local status
  if [[ "$local_status" == "up" ]]; then
    echo -e "  ${GREEN}●${NC} $local_node (local) — ${GREEN}serving on :$PORT${NC}"
  else
    echo -e "  ${RED}●${NC} $local_node (local) — ${RED}NOT serving${NC}"
  fi

  # Peer status
  while IFS='|' read -r _ name url status identity; do
    [[ -z "$name" ]] && continue
    if [[ "$status" == "up" ]]; then
      echo -e "  ${GREEN}●${NC} $name ($identity) — ${GREEN}reachable${NC}"
    else
      echo -e "  ${RED}●${NC} $name — ${RED}unreachable${NC} ($url)"
    fi
  done <<< "$results"

  echo ""
  if [[ $healthy -eq $total ]] && [[ "$local_status" == "up" ]]; then
    echo -e "  ${GREEN}✅ $healthy/$total peers healthy${NC}"
  else
    echo -e "  ${YELLOW}⚠️  $healthy/$total peers healthy${NC}"
  fi
}

check_peers
