#!/usr/bin/env bash
# Federation Config Generator
# Generates maw.config.json for N-node federation
#
# Usage:
#   ./federation-config-gen.sh              # Interactive mode
#   ./federation-config-gen.sh 2            # Quick 2-node setup
#   ./federation-config-gen.sh 3            # Quick 3-node setup
#   ./federation-config-gen.sh --help       # Show help
#
# 🤖 Generated by Federation Oracle 🗺️

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

show_help() {
  echo ""
  echo -e "${CYAN}Federation Config Generator${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  echo "Generates maw.config.json files for an N-node federation."
  echo ""
  echo "Usage:"
  echo "  $0              Interactive mode"
  echo "  $0 <N>          Quick mode — generate configs for N nodes"
  echo "  $0 --help       Show this help"
  echo ""
  echo "Examples:"
  echo "  $0 2            Two-node federation"
  echo "  $0 3            Three-node federation"
  echo ""
  echo "Output:"
  echo "  Creates a federation-configs/ directory with one JSON file per node."
  echo "  Copy each file to its machine at ~/.config/maw/maw.config.json"
  echo ""
}

# Generate token
gen_token() {
  openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))" 2>/dev/null || echo "change-me-$(date +%s)-minimum-16-chars"
}

main() {
  if [[ "${1:-}" == "--help" ]] || [[ "${1:-}" == "-h" ]]; then
    show_help
    exit 0
  fi

  echo ""
  echo -e "${CYAN}🗺️  Federation Config Generator${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""

  # Number of nodes
  if [[ -n "${1:-}" ]]; then
    NUM_NODES="$1"
  else
    echo -n "How many nodes in your federation? [2]: "
    read -r NUM_NODES
    NUM_NODES="${NUM_NODES:-2}"
  fi

  if [[ "$NUM_NODES" -lt 2 ]]; then
    echo -e "${RED}Federation needs at least 2 nodes.${NC}"
    exit 1
  fi

  # Token
  TOKEN=$(gen_token)
  echo -e "${GREEN}Generated token:${NC} $TOKEN"
  echo ""

  # Collect node info
  declare -a NAMES
  declare -a IPS
  PORT=3456

  for ((i=1; i<=NUM_NODES; i++)); do
    echo -e "${YELLOW}--- Node $i of $NUM_NODES ---${NC}"

    if [[ -z "${1:-}" ]] || [[ "$NUM_NODES" -le 1 ]]; then
      # Interactive mode
      echo -n "  Node name (e.g., laptop, desktop, server): "
      read -r name
      echo -n "  IP address (e.g., 192.168.1.100): "
      read -r ip
    else
      # Quick mode — use default names
      case $i in
        1) name="alpha"; ip="MACHINE_${i}_IP" ;;
        2) name="beta";  ip="MACHINE_${i}_IP" ;;
        3) name="gamma"; ip="MACHINE_${i}_IP" ;;
        4) name="delta"; ip="MACHINE_${i}_IP" ;;
        5) name="epsilon"; ip="MACHINE_${i}_IP" ;;
        *) name="node-$i"; ip="MACHINE_${i}_IP" ;;
      esac
      echo -e "  Name: ${GREEN}$name${NC}  IP: ${GREEN}$ip${NC}"
    fi

    NAMES+=("$name")
    IPS+=("$ip")
    echo ""
  done

  # Create output directory
  OUTPUT_DIR="federation-configs"
  mkdir -p "$OUTPUT_DIR"

  echo -e "${CYAN}Generating configs...${NC}"
  echo ""

  # Generate config for each node
  for ((i=0; i<NUM_NODES; i++)); do
    NODE_NAME="${NAMES[$i]}"
    CONFIG_FILE="$OUTPUT_DIR/${NODE_NAME}.config.json"

    # Build peers array (all nodes except this one)
    PEERS=""
    for ((j=0; j<NUM_NODES; j++)); do
      if [[ $i -ne $j ]]; then
        if [[ -n "$PEERS" ]]; then
          PEERS="$PEERS,"
        fi
        PEERS="$PEERS
    {\"name\": \"${NAMES[$j]}\", \"url\": \"http://${IPS[$j]}:$PORT\"}"
      fi
    done

    # Write config
    cat > "$CONFIG_FILE" << ENDCONFIG
{
  "node": "$NODE_NAME",
  "port": $PORT,
  "host": "0.0.0.0",
  "federationToken": "$TOKEN",
  "namedPeers": [$PEERS
  ],
  "agents": {}
}
ENDCONFIG

    echo -e "  ${GREEN}✅${NC} $CONFIG_FILE"
  done

  echo ""
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${GREEN}Done!${NC} Created $NUM_NODES config files in ${OUTPUT_DIR}/"
  echo ""
  echo "Next steps:"
  echo "  1. Replace MACHINE_*_IP placeholders with real IPs"
  echo "  2. Copy each file to its machine:"
  echo ""
  for ((i=0; i<NUM_NODES; i++)); do
    echo "     scp $OUTPUT_DIR/${NAMES[$i]}.config.json USER@${IPS[$i]}:~/.config/maw/maw.config.json"
  done
  echo ""
  echo "  3. Start maw serve on each machine:"
  echo "     maw serve"
  echo ""
  echo "  4. Verify from each machine:"
  echo "     maw federation status"
  echo ""
  echo -e "${CYAN}Token (save this!):${NC} $TOKEN"
  echo ""
  echo -e "🗺️  ${CYAN}Happy federating!${NC}"
}

main "$@"
